[package]
name = "ht16k33-diet"
version = "0.1.0"
authors = ["Nils Eriksson <nils.edvin.eriksson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
bounded-integer = "0.2.3"
embedded-hal = "0.2.4"

[dev-dependencies]
embedded-hal-mock  = "0.7.2"