[package]
name = "ht16k33-lite"
version = "0.1.0"
authors = ["Nils Eriksson <nils.edvin.eriksson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Driver for the Holtek HT16K33 'RAM Mapping 16*8 LED Controller Driver with keyscan'"
repository = "https://github.com/sesar54/ht16k33-lite"
keywords = ["driver", "led", "ht16k33", "no-std", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
embedded-hal = "0.2.4"

[dependencies.bounded-integer]
version = "0.3.0"
features = ["step_trait"]
